version: "3.2"

services:
  client:
    build: client
    hostname: client
    ports:
        - 4040:4040
    tty: true
    volumes: 
        - ./conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
        - ./conf/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
        - ./conf/mapred-site.xml:/opt/hadoop/etc/hadoop/mapred-site.xml
        - ./conf/yarn-site.xml:/opt/hadoop/etc/hadoop/yarn-site.xml
        - ./conf/hbase-site.xml:/opt/hbase/conf/hbase-site.xml
        - ./conf/hive-site.xml:/opt/hive/conf/hive-site.xml
        - volume_hive:/hive
        - ./program:${WORKSPACE_ROOT}/program
    working_dir: ${WORKSPACE_ROOT}/program

#   jupyter:
#     image: jupyter/pyspark-notebook
#     ports:
#         - 8888:8888
#     volumes: 
#         - ./program:${WORKSPACE_ROOT}/program
#     working_dir: ${WORKSPACE_ROOT}/program

volumes:
  volume_hive:

networks:
  default:
    external:
      name: hadoop_network
